name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Select Xcode version (14.0)
        run: |
          sudo xcode-select --switch /Applications/Xcode_14.0.app
      - name: Build IPA
        run: |
          xcodebuild build -scheme Santander -configuration "Release" CODE_SIGNING_ALLOWED="NO" CODE_SIGNING_REQUIRED="NO" CODE_SIGN_IDENTITY="" BUILD_DIR=${{ github.workspace }}/xcodebuild
          mkdir -p ${{ github.workspace }}/ipadir/Payload
          cp -R ${{ github.workspace }}/xcodebuild/Release-iphoneos/Santander.app ${{ github.workspace }}/ipadir/Payload
          cd ${{ github.workspace }}/ipadir
          
          brew install ldid
          ldid -S../entitlements.plist Payload/Santander.app/Santander
          zip -r ${{ github.workspace }}/Santander.ipa .
      - name: Upload IPA
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Santander
          path: ${{ github.workspace }}/Santander.ipa
